info:
  title: "REST API Configs V1"
  description: "Sample Configurations"
services:
  oms:
    name: "Order Management Service"
    base_url: "http://myoms.com"
    version:
      v1:
        create_order:
          path: "/api/v1/orders/create"
          verb: "POST"
      v2:
        create_order:
          path: "/api/v2/orders/create"
          verb: "POST"
  laas:
    name: "Logistic Management Service"
    base_url: "http://mylaas.com"
    version:
      v1:
        create_shipment:
          path: "/api/v1/shipment/create"
          verb: "POST"
      v2:
        create_shipment:
          path: "/api/v2/orders/create"
          verb: "POST"