info:
  title: "REST API Configs V1"
  description: "Sample Configurations"
services:
  oms:
    name: "Order Management Service"
    base_url: "http://myoms.com"
    version:
      v1:
        create_order:
          path: "/api/v1/orders/create"
          verb: "POST"
      v2:
        create_order:
          path: "/api/v2/orders/create"
          verb: "POST"
  product:
    name: "Product Management Service"
    base_url: "https://fakestoreapi.com"
    version:
      v1:
        get_products:
          path: "/products"
          verb: "GET"
        get_product:
          path: "/products/1"
          verb: "GET"
      v2:
        create_shipment:
          path: "/api/v2/orders/create"
          verb: "POST"